/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_com_hst_ptr_SP_PTR_PR1000 */

#ifndef _Included_br_com_hst_ptr_SP_PTR_PR1000
#define _Included_br_com_hst_ptr_SP_PTR_PR1000
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_com_hst_ptr_SP_PTR_PR1000
 * Method:    PTR_PR1000_initialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_br_com_hst_ptr_SP_1PTR_1PR1000_PTR_1PR1000_1initialize
  (JNIEnv *, jobject);

/*
 * Class:     br_com_hst_ptr_SP_PTR_PR1000
 * Method:    PTR_PR1000_finalize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_br_com_hst_ptr_SP_1PTR_1PR1000_PTR_1PR1000_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     br_com_hst_ptr_SP_PTR_PR1000
 * Method:    PTR_PR1000_reset
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_br_com_hst_ptr_SP_1PTR_1PR1000_PTR_1PR1000_1reset
  (JNIEnv *, jobject);

/*
 * Class:     br_com_hst_ptr_SP_PTR_PR1000
 * Method:    PTR_PR1000_printLine
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_br_com_hst_ptr_SP_1PTR_1PR1000_PTR_1PR1000_1printLine
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     br_com_hst_ptr_SP_PTR_PR1000
 * Method:    PTR_PR1000_printDoc
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_br_com_hst_ptr_SP_1PTR_1PR1000_PTR_1PR1000_1printDoc
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     br_com_hst_ptr_SP_PTR_PR1000
 * Method:    PTR_PR1000_printRawData
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_br_com_hst_ptr_SP_1PTR_1PR1000_PTR_1PR1000_1printRawData
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     br_com_hst_ptr_SP_PTR_PR1000
 * Method:    PTR_PR1000_getStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_br_com_hst_ptr_SP_1PTR_1PR1000_PTR_1PR1000_1getStatus
  (JNIEnv *, jobject);

/*
 * Class:     br_com_hst_ptr_SP_PTR_PR1000
 * Method:    PTR_PR1000_isDocumentInserted
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_br_com_hst_ptr_SP_1PTR_1PR1000_PTR_1PR1000_1isDocumentInserted
  (JNIEnv *, jobject);

/*
 * Class:     br_com_hst_ptr_SP_PTR_PR1000
 * Method:    PTR_PR1000_IOControl
 * Signature: (ILjava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_br_com_hst_ptr_SP_1PTR_1PR1000_PTR_1PR1000_1IOControl
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     br_com_hst_ptr_SP_PTR_PR1000
 * Method:    PTR_PR1000_getVersion
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_br_com_hst_ptr_SP_1PTR_1PR1000_PTR_1PR1000_1getVersion
  (JNIEnv *, jobject, jobject);

/*
 * Class:     br_com_hst_ptr_SP_PTR_PR1000
 * Method:    PTR_PR1000_receiptCut
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_br_com_hst_ptr_SP_1PTR_1PR1000_PTR_1PR1000_1receiptCut
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
